# Generated by Django 3.2.5 on 2021-08-24 00:24

import django.core.validators
from django.db import migrations, models
import register.validators


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="O numero de telefone precisa atender o padrão: '99 99999-9999' ou '99 9999-9999'", regex='(\\(?\\d{2}\\)?\\s)?(\\d{4,5}\\-\\d{4})')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[register.validators.validate_CNPJ], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[register.validators.validate_CPF], verbose_name='CPF'),
        ),
    ]
