# Generated by Django 3.2.5 on 2021-08-26 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210824_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="O numero de telefone precisa atender o padrão: '99 99999-9999' ou '99 9999-9999'", regex='(\\(?\\d{2}\\)?\\s)?(\\d{4,5}\\-\\d{4})')], verbose_name='Phone'),
        ),
    ]
