# Generated by Django 3.2.5 on 2021-08-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_rename_user_docs_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='customer',
            new_name='user',
        ),
    ]
