# Generated by Django 3.2.5 on 2021-08-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_customer_docs_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='user',
            new_name='name',
        ),
    ]
