# Generated by Django 3.2.5 on 2021-08-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_user_docs_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='name',
            new_name='user',
        ),
    ]
